<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>MVC</title>
    <script type="text/javascript" src="js/scripts.js"></script>
    <link rel="stylesheet" type="text/css" href="css/styles.css" />
</head>

<body>
<a href="/1">Home</a>
<a href="/1/index.php?controller=book&amp;action=index">Book</a>
<a href="/1/index.php?controller=feedback&amp;action=contact">Contact us</a>

<hr>

<?= $content ?>

</body>
</html>